# Generated by Django 2.1.4 on 2019-03-25 07:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20190325_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlepost',
            old_name='articke_tag',
            new_name='article_tag',
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 25, 7, 19, 40, 591157, tzinfo=utc)),
        ),
    ]
